services:

  ts-lenovo:
    image: tailscale/tailscale:latest
    hostname: ts-lenovo
    restart: unless-stopped
    network_mode: bridge
    ports:
      - "127.0.0.1:1080:1080/tcp"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    volumes:
      - ./tailscale:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    environment:
      TS_AUTHKEY: ${TS_AUTHKEY}
      TS_STATE_DIR: /var/lib/tailscale
      TS_USERSPACE: "false"
      TS_EXTRA_ARGS: >-
        --accept-routes
      TZ: Europe/Amsterdam

  ts-socks5:
    image: serjs/go-socks5-proxy:latest
    restart: unless-stopped
    network_mode: "service:ts-lenovo"
    depends_on:
      - ts-lenovo
    environment:
      REQUIRE_AUTH: false
      PROXY_USER: username
      PROXY_PASSWORD: password
      PROXY_PORT: 1080
